# Generated by Django 4.2.6 on 2023-11-08 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="equipe",
            new_name="id_equipe",
        ),
    ]
