# Generated by Django 4.2.6 on 2023-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_equipe_userprofile_id_equipe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
