# Generated by Django 4.2.6 on 2023-11-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=128)),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("Aministrador", "Administrador"),
                            ("Tech Lead", "Tech Lead"),
                            ("Desenvolvedor", "Desenvolvedor"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
