# Generated by Django 4.2.6 on 2023-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id_task", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_conclusao", models.DateField()),
            ],
        ),
    ]
