# Generated by Django 4.2.6 on 2023-11-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id_task", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateField(auto_now_add=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("Facil", "Fácil"),
                            ("Medio", "Medio"),
                            ("Dificil", "Dificil"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tasks",
        ),
    ]
