# Generated by Django 4.2.6 on 2023-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Em Andamento", "Em Andamento"),
                    ("Concluido", "Concluido"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
