# Generated by Django 4.2.6 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="data_criacao",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
