# Generated by Django 4.2.6 on 2023-11-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_data_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dificuldade",
            field=models.CharField(
                choices=[
                    ("Facil", "Facil"),
                    ("Medio", "Medio"),
                    ("Dificil", "Dificil"),
                ],
                max_length=20,
            ),
        ),
    ]
