# Generated by Django 4.2.6 on 2023-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id_empresa", models.AutoField(primary_key=True, serialize=False)),
                ("nome_empresa", models.CharField(max_length=150)),
            ],
        ),
    ]
